name: jop_task
description: "A new Flutter project."

publish_to: 'none'


version: 1.0.0+1

environment:
  sdk: ^3.5.3


dependencies:
  flutter:
    sdk: flutter



  cupertino_icons: ^1.0.8
  dio: ^5.7.0
  flutter_svg: ^2.0.16
  country_code_picker_plus: ^0.0.9
  dartz: ^0.10.1
  flutter_bloc: ^8.1.6
  get_it: ^8.0.3
  shared_preferences: ^2.3.3
  flutter_secure_storage: ^9.2.2
  dotted_border: ^2.1.0
  image_picker: ^1.1.2
  intl: ^0.20.1
  image: ^4.5.2
  qr_code_scanner: ^1.0.1
  flutter_image_compress: ^2.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^4.0.0


flutter:


  uses-material-design: true


  assets:
     - assets/fonts/
     - assets/images/
     - assets/svg/

  fonts:
     - family: DMSans
       fonts:
         - asset: assets/fonts/DMSans.ttf


  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
